

services:
  backend:
    build: .
    container_name: finance_backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  postgres:
    image: postgres:15
    container_name: finance_postgres
    environment:
      POSTGRES_DB: assets_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:

networks:
  finance_net:
    driver: bridge

    
